// import Router from "../koa-router"
const Router = require('koa-router')
const news = require('./news')
const studentrRegister = require('./studentrRegister')
const workerRegister = require('./workerRegister')
const login = require('./login')
const getUrl = require('./getImg')
const getExampleList = require('./getExampleList')
const getLeaveMessage = require('./getLeaveMessage')
const publishedComments = require('./publishedComments')
const managementPhoto = require('./managementPhoto')
const classPhotoAlbum = require('./classPhotoAlbum')
const classMessageBoard = require('./classMessageBoard')
const manageMessageBoard = require('./manageMessageBoard')
const deleteMessage = require('./deleteMessage')
const postClassMessageBoard = require('./postClassMessageBoard')
const postClassAddressBook = require('./postClassAddressBook')
const getClassAddressBook = require('./getClassAddressBook')
const getManageClass = require('./getManageClass')
const modifyManageClass = require('./modifyManageClass')
const serch = require('./serch')
const getPostListst = require('./getPostListst')
const data = require('./data')
const tjnj = require('./tjnj')
const njwh = require('./njwh')
const xgnj = require('./xgnj')
const scnj = require('./scnj')
const njxlk = require('./njxlk')
const tjbj = require('./tjbj')
const bjwh = require('./bjwh')
const xgbj = require('./xgbj')
const scbj = require('./scbj')
const xsjl = require('./xsjl')
const tjxs = require('./tjxs')
const xswh = require('./xswh')
const xgxs = require('./xgxs')
const scxs = require('./scxs')
const ss = require('./ss')
let router = new Router()

router.use(news.routes())
router.use(studentrRegister.routes())
router.use(workerRegister.routes())
router.use(login.routes())
router.use(getUrl.routes())
router.use(getExampleList.routes())
router.use(getLeaveMessage.routes())
router.use(publishedComments.routes())
router.use(managementPhoto.routes())
router.use(classPhotoAlbum.routes())
router.use(classMessageBoard.routes())
router.use(manageMessageBoard.routes())
router.use(deleteMessage.routes())
router.use(postClassMessageBoard.routes())
router.use(postClassAddressBook.routes())
router.use(getClassAddressBook.routes())
router.use(getManageClass.routes())
router.use(modifyManageClass.routes())
router.use(serch.routes())
router.use(getPostListst.routes())
router.use(data.routes())
router.use(tjnj.routes())
router.use(njwh.routes())
router.use(xgnj.routes())
router.use(scnj.routes())
router.use(njxlk.routes())
router.use(tjbj.routes())
router.use(bjwh.routes())
router.use(xgbj.routes())
router.use(scbj.routes())
router.use(xsjl.routes())
router.use(tjxs.routes())
router.use(xswh.routes())
router.use(xgxs.routes())
router.use(scxs.routes())
router.use(ss.routes())
module.exports = router
